variables:
  DOCKER_DRIVER: overlay
  FILES_TO_CRITIC: critichtml critictest

stages:
- test

perl_critic_html:
  stage: test
  image: olegfiksel/perl_critic:latest
  script:
    - cd critic_html
    - critichtml $FILES_TO_CRITIC
    - cd ../
    - mv critic_html/critic_html perl-critic-html
  artifacts:
    expire_in: 1 week
    paths:
    - perl-critic-html

perl_critic_text:
  stage: test
  image: olegfiksel/perl_critic:latest
  script:
    - cd critic_html
    - critictest $FILES_TO_CRITIC
